project:
  type: book
  output-dir: docs

book:
  title: Statistical Learning with R
  author: "Guillaume Gilles"
  date: "12/11/2024"
  
  chapters:
    - index.qmd
    - preface.qmd
  
    - part: DESCRIPTIVE STATISTICS
      chapters:
        - descriptive-part/definition-key-terms.qmd
        - descriptive-part/data-sampling-variation.qmd
        - descriptive-part/variance.qmd
  
    - part: INFERENTIAL STATISTICS
      chapters: 
        - sets-combinatorial-analysis.qmd

  appendices: 
    - appendices/lexicon.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: united
      dark: solar



