project:
  type: book
  output-dir: docs

book:
  title: Statistical Learning with R
  author: "Guillaume Gilles"
  date: "12/11/2024"
  
  chapters:
    - index.qmd
    - preface.qmd
  
    - part: DESCRIPTIVE STATISTICS
      chapters:
        - data.qmd
        - qualitative.qmd
        - quantitative.qmd
  
    - part: INFERENTIAL STATISTICS
      chapters: 
        - sets-combinatorial-analysis.qmd
    
    - part: STATISTICAL LEARNING
      chapters:
        - tidyverse.qmd
        - variance-biais.qmd
        - workflow.qmd

  appendices:
    - sampling.qmd
    - glossary.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: united
      dark: solar



