project:
  type: book
  output-dir: docs

book:
  title: Statistical Learning with R
  author: "Guillaume Gilles"
  date: "12/11/2024"
  chapters:
    - index.qmd
    - preface.qmd
    - part: Descriptive Statistics
      chapter:
        - definition-key-terms.qmd
        - data-sampling-variation.qmd
    - part: Inferential Statistics
      chapter: 
        - sets-combinatorial-analysis.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: united
      dark: solar



