project:
  type: book
  output-dir: docs

book:
  title: Statistical Learning with R
  author: "Guillaume Gilles"
  date: "12/11/2024"
  
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
  
    - part: DESCRIPTIVE STATISTICS
      chapters:
        - descriptive/dataset.qmd
        - descriptive/central-tendency.qmd
        - descriptive/variability.qmd
        - descriptive/data-visualization.qmd
  
    - part: INFERENTIAL STATISTICS
      chapters: 
        - inferential/sets-combinatorial-analysis.qmd
    
    - part: STATISTICAL LEARNING
      chapters:
        - statistical-learning/tidyverse.qmd
        - statistical-learning/variance-biais.qmd

  appendices: 
    - appendices/glossary.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: united
      dark: solar



