# Measures of the center of the data

title: Mean
desc: ''
updated: 1729068716853
created: 1729068716853
isDir: false
id_imported: dqhs5pjx245a44k5nweepis
title_imported: Statistical Mean
desc_imported: Moyenne
updated_imported: 1711442506750
created_imported: 1670271439145
---

La moyenne, notée m ou x- (x barre), est le centre de gravité

## Arithmetic Mean

## Weighted Mean

La moyenne arithmétique est la somme des valeurs divisée par le nombre d'individus :

$$
\bar{X} = \frac{1}{n} \cdot \sum_{i = 1}^n x_i
$$

## Références

- https://fr.wikipedia.org/wiki/Statistique_descriptive

title: Median
desc: ''
updated: 1729068716853
created: 1729068716853
isDir: false
id_imported: rxxilp2zi8bfjr7lyalwjt5
title_imported: Statistical Mediane
desc_imported: Médiane
updated_imported: 1711442423801
created_imported: 1670271512599
---

La **médiane**, désignée par Me, est la valeur de la variable statistique qui sépare la population ou l’échantillon en deux sous-ensembles égaux. Il y a 50% de la population au-dessus de la médiane et 50% de la population en dessous de la médiane.

La médiane est la valeur centrale qui partage l'échantillon en 2 groupes de même effectif : 50 % au-dessus et 50 % en dessous. La médiane peut avoir une valeur différente de la moyenne. En France (et d'ailleurs dans la plupart des pays), le salaire médian est inférieur au salaire moyen : il y a beaucoup de smicards et peu de gros salaires. Cependant, les gros salaires tirent la moyenne vers le haut.

En général, une médiane est, dans une série ordonnée, une valeur M telle qu'il y ait autant de valeurs supérieures ou égales à M que de valeur inférieures ou égales à M. exemple : 1 3 5 7 9 la médiane est 5

## Références

- https://fr.wikipedia.org/wiki/Statistique_descriptive

title: Mode
desc: ''
updated: 1729068716853
created: 1729068716853
isDir: false
id_imported: o4r1kk10jywt83wmm0ez0cf
title_imported: Statistical Mode
desc_imported: null
updated_imported: 1711442374958
created_imported: 1670271557198
---

Le **mode**, désigné par Mo, est la valeur de la variable statistique la plus fréquente. Dans le cas d’une variable statistique continue, le mode est appelé **classe modale**. Le mode, ou classe modale, n’est pas obligatoirement unique. Il peut exister plusieurs valeurs les plus fréquente dans une population ou échantillon.
