# Data, Sampling, and Variation in Data and Sampling Data

Before anything else, statistical modeling requires raw materials such
as **data**. It is the building blocs of all models. In this chapter
you'll learn to recognize different types of data.

Data comes in two flavors: **quantitative**  and **qualitative**.

##  Quantitative data

Quantitative data are the result of counting or measuring attributes of
a population. Amount of money, pulse rate, weight, number of people living
in your town, and number of students who take statistics are examples of
quantitative data. Quantitative data may be either **discrete** or
**continuous**.

### Quantitative discrete data

All data that are the result of counting are called quantitative discrete
data. These data take on only certain numerical values. If you count the
number of phone calls you receive for each day of the week, you might get
values such as zero, one, two, or three.

### Quantitative continuous data

Data that are not only made up of counting numbers, but that may include
fractions, decimals, or irrational numbers, are called quantitative 
continuous data. Continuous data are often the results of measurements
like lengths, weights, or times. A list of the lengths in minutes for all
the phone calls that you make in a week, with numbers like $2.4$, $7.5$,
or $11.0$, would be quantitative continuous data.

## Qualitative data

Qualitative data are the result of categorizing or describing attributes
of a population. Qualitative data are also often called **categorical data**.
Hair color, blood type, ethnic group, the car a person drives, and the
street a person lives on are examples of qualitative (categorical) data.

Qualitative (categorical) data are generally described by words or letters.
For instance, hair color might be black, dark brown, light brown, blonde,
gray, or red. Blood type might be AB+, O-, or B+. Researchers often
prefer to use quantitative data over qualitative (categorical) data because
it lends itself more easily to mathematical analysis. For example, it
does not make sense to find an average hair color or blood type.

Qualitative data also comes in 2 flavors:

- **Ordinal**: The categories of the variable can be arranged in a natural
  order, like school grades.  
- **Nominal**: Conversely, nominal qualitative values cannot be ranked in
  order, like hair color.

## Where does data comes from?

### Population and Sample

In statistics, we generally want to study a population. You can think
of a population as a collection of persons, things, or objects under
study. To study the population, we select a sample.

Because it takes a lot of time and money to examine an entire population,
sampling is a very practical technique. If you wished to compute the
overall grade point average at your school, it would make sense to select
a sample of students who attend the school. The data collected from the
sample would be the students' grade point averages. In presidential
elections, opinion poll samples of 1,000–2,000 people are taken. The
opinion poll is supposed to represent the views of the people in the
entire country. Manufacturers of canned carbonated drinks take samples to
determine if a 16 ounce can contains 16 ounces of carbonated drink.

The idea of sampling is to select a portion (or subset) of the larger
population and study that portion (the sample) to gain information about
the population.

> Data are the result of sampling from a population. You can find more
> information in the [](sampling.qmd) section of the appendices.

### Statistic and Parameter

From the sample data, we can calculate a **statistic**. A statistic is
a number that represents a property of the sample. For example, if we
consider one math class to be a sample of the population of all math
classes, then the average number of points earned by students in that
one math class at the end of the term is an example of a statistic. The
statistic is an estimate of a population **parameter**.

A parameter is a numerical characteristic of the whole population that
can be estimated by a statistic. Since we considered all math classes to
be the population, then the average number of points earned per student
over all the math classes is an example of a parameter.

## Is statistics accurate then?

One of the main concerns in the field of statistics is how accurately a
statistic estimates a population's parameter. The accuracy really depends
on how well the sample represents the population. The sample must contain
the characteristics of the population in order to be arepresentative
sample.

## Variables

A **variable**, usually notated by capital letters such as $X$ and $Y$, is
a characteristic or measurement that can be determined for each member of
a population. Variables may be quantitative or qualitative (categorical).

for example, if $X$ equal the number of points earned by one math student
at the end of a term, then $X$ is a quantitative variable. If $Y$ be a
person's party affiliation, then some examples of $Y$ include Republican,
Democrat, and Independent. $Y$ is a qualitative (categorical) variable.
We could do some math with values of $X$ (calculate the average number
of points earned, for example), but it makes no sense to do math with
values of $Y$ (calculating an average party affiliation makes no sense).

Data are the actual values of the variable. They may be numbers or they
may be words. Lowercase letters like $x$ or $y$ generally are used to
represent data values.

## Exercices

### Example 1

Determine what the key terms refer to in the following study. We want to
know the average (mean) amount of money first year college students
spend at ABC College on school supplies that do not include books. We
randomly surveyed 100 first year students at the college. Three of
those students spent $150, $200, and $225, respectively.


::: {.callout-tip collapse="true"}
# Solution

- The **population** is all first year students attending ABC College
  this term.
- The **sample** could be all students enrolled in one section of a
  beginning statistics course at ABC College (although this sample may
  not represent the entire population).
- The **parameter** is the average (mean) amount of money spent
  (excluding books) by first year college students at ABC College this
  term: the population mean.
- The **statistic** is the average (mean) amount of money spent
  (excluding books) by first year college students in the sample.
- The **variable** could be the amount of money spent (excluding books)
  by one first year student. Let X = the amount of money spent (excluding
  books) by one first year student attending ABC College.
- The **data** are the dollar amounts spent by the first year students.
  Examples of the data are $150, $200, and $225.
:::

### Example 2

Determine what the key terms refer to in the following study.

A study was conducted at a local college to analyze the average cumulative
GPA’s of students who graduated last year. For each statement below find
the appropriate statistical term.

1. The cumulative GPA of one student who graduated from the college last
  year.
2. $3.65$, $2.80$, $1.50$, $3.90$
3. A group of students who graduated from the college last year, randomly
  selected.
4. The average cumulative GPA of students who graduated from the college
  last year.
5. All students who graduated from the college last year.
6. the average cumulative GPA of students in the study who graduated from
  the college last year.

::: {.callout-tip collapse="true"}
# Solution

1. Population: **5**
2. Statistic: **6**
3. Parameter: **4**
4. Sample: **3**
5. Variable: **1**
6. Data: **2**
:::

### Example 3

Determine what the key terms refer to in the following study.

As part of a study designed to test the safety of electric automobiles,
the National Transportation Safety Board collected and reviewed data
about the effects of an automobile crash on test dummies. Here is the
criterion they used:

| Speed at which cars crashed |	Location of “drive” (i.e. dummies) |
|:--------------------------- | :----------------------------------|
| 35 miles/hour 	          | Front Seat                         |

Cars with dummies in the front seats were crashed into a wall at a speed
of 35 miles per hour. We want to know the proportion of dummies in the
driver’s seat that would have had head injuries, if they had been actual
drivers. We start with a simple random sample of 75 cars.

::: {.callout-tip collapse="true"}
# Solution

- The **population** is all cars containing dummies in the front seat.
- The **sample** is the 75 cars, selected by a simple random sample.
- The **parameter** is the proportion of driver dummies (if they had been
  real people) who would have suffered head injuries in the population.
- The **statistic** is proportion of driver dummies (if they had been
  real people) who would have suffered head injuries in the sample.
- The **variable** $X =$ whether a dummy (if it had been a real person)
  would have suffered head injuries.
- The **data** are either: yes, had head injury, or no, did not.
:::