---
title: Data, Sampling, and Variation in Data and Sampling Data
---

Data may come from a population or from a sample. Lowercase letters like $x$ or
$y$ generally are used to represent data values. Most data can be put into the
following categories:

- Qualitative
- Quantitative

**Qualitative data** are the result of categorizing or describing attributes of
a population. Qualitative data are also often called **categorical data**. Hair
color, blood type, ethnic group, the car a person drives, and the street a
person lives on are examples of qualitative (categorical) data. Qualitative
(categorical) data are generally described by words or letters. For instance,
hair color might be black, dark brown, light brown, blonde, gray, or red. Blood
type might be AB+, O-, or B+. Researchers often prefer to use quantitative data
over qualitative (categorical) data because it lends itself more easily to
mathematical analysis. For example, it does not make sense to find an average
hair color or blood type.

**Quantitative data** are always numbers. Quantitative data are the result of
**counting** or **measuring** attributes of a population. Amount of money,
pulse rate, weight, number of people living in your town, and number of
students who take statistics are examples of quantitative data. Quantitative
data may be either **discrete** or **continuous**.

All data that are the result of counting are called **quantitative discrete
data**. These data take on only certain numerical values. If you count the number
of phone calls you receive for each day of the week, you might get values such
as zero, one, two, or three.

Data that are not only made up of counting numbers, but that may include
fractions, decimals, or irrational numbers, are called **quantitative
continuous data**. Continuous data are often the results of measurements like
lengths, weights, or times. A list of the lengths in minutes for all the phone
calls that you make in a week, with numbers like $2.4$, $7.5$, or $11.0$,
would be quantitative continuous data.

::: {.callout-note}
### Try it!
The data are the number of machines in a gym. You sample five gyms. One gym
has 12 machines, one gym has 15 machines, one gym has ten machines, one gym
has 22 machines, and the other gym has 20 machines. What type of data is this?
:::

::: {.callout-tip collapse="true"}
### Solution
Quantitative discrete data
:::

::: {.callout-note}
### Try it!
The data are the areas of lawns in square feet. You sample five houses. The
areas of the lawns are 144 sq. feet, 160 sq. feet, 190 sq. feet, 180 sq. feet,
and 210 sq. feet. What type of data is this?
:::

::: {.callout-tip collapse="true"}
### Solution
Quantitative continuous data
:::

::: {.callout-note}
### Example
You go to the supermarket and purchase three cans of soup (19 ounces tomato 
bisque, 14.1 ounces lentil, and 19 ounces Italian wedding), two packages of
nuts (walnuts and peanuts), four different kinds of vegetable (broccoli,
cauliflower, spinach, and carrots), and two desserts (16 ounces pistachio ice
cream and 32 ounces chocolate chip cookies).
:::

::: {.callout-tips collapse="true"}
### Solution
One possible solution could be:

- The three cans of soup, two packages of nuts, four kinds of vegetables and
two desserts are **quantitative discrete data** because you count them.
- The weights of the soups (19 ounces, 14.1 ounces, 19 ounces) are **quantitative
continuous data** because you measure weights as precisely as possible.
- Types of soups, nuts, vegetables and desserts are **qualitative data** because
they are categorical.
:::

::: {.callout-note}
### try it!
The registrar at State University keeps records of the number of credit hours
students complete each semester. The data collected are summarized in the
histogram. The class boundaries are 10 to less than 13, 13 to less than 16, 16
to less than 19, 19 to less than 22, and 22 to less than 25.


What type of data does this graph show?
:::

::: {.callout-tip collapse="true"}
### Solution
Quantitative continuous data
:::

## Qualitative Data Discussion

Below are tables comparing the number of part-time and full-time students at De
Anza College and Foothill College enrolled for the most recent spring quarter.
The tables display counts (frequencies) and percentages or proportions (relative
frequencies). The percent columns make comparing the same categories in the
colleges easier. Displaying percentages along with the numbers is often helpful,
but it is particularly important when comparing sets of data that do not have
the same totals, such as the total enrollments for both colleges in this example.
Notice how much larger the percentage for part-time students at Foothill College
is compared to De Anza College.

| De Anza College | Foothill College |
| | Number | Percent | | Number | Percent|
|-|--------|---------|-|--------|--------|
|Full-time | 9,200 | 40.9% | Full-time | 4,059 | 28.6% |
| Part-time| 13,296| 59.1%| Part-time | 10,124 | 71.4% |
|Total| 22,496 | 100% | Total | 14,183 | 100% |

<!-- ```{python}
import pandas as pd
data = {"product_name":["Keyboard","Mouse", "Monitor", "CPU","CPU", "Speakers", pd.NaT],
        "Unit_Price":[500,200, 5000.235, 10000.550, 10000.550, 250.50,None],
        "No_Of_Units":[5,5, 10, 20, 20, 8,pd.NaT],
        "Available_Quantity":[5,6,10,"Not Available","Not Available", pd.NaT, pd.NaT],
        "Available_Since_Date":['11/5/2021', '4/23/2021', '08/21/2021', '09/18/2021', '09/18/2021', '01/05/2021', pd.NaT]
       }
df = pd.DataFrame(data)
df = df.astype({"Unit_Price": float})
df
``` -->

Tables are a good way of organizing and displaying data. But graphs can be even
more helpful in understanding the data. There are no strict rules concerning
which graphs to use. Two graphs that are used to display qualitative 
(categorical) data are **pie charts** and **bar graphs**.

- In a pie chart, categories of data are represented by wedges in a circle and
 are proportional in size to the percent of individuals in each category.
- In a bar graph, the length of the bar for each category is proportional to the
number or percent of individuals in each category. Bars may be vertical or
horizontal.
- A Pareto chart consists of bars that are sorted into order by category size
(largest to smallest).

```R
ggplot()
```

:::{callout-important}
It is a good idea to look at a variety of graphs to see which is the most
helpful in displaying the data. We might make different choices of what we
think is the “best” graph depending on the data and the context. Our choice
also depends on what we are using the data for.
:::

:::{callout-tip}
## Percentages That Add to More (or Less) Than 100%

Sometimes percentages add up to be more than 100% (or less than 100%). In the
graph, the percentages add to more than 100% because students can be in more
than one category. A bar graph is appropriate to compare the relative size of
the categories. **A pie chart cannot be used**. It also could not be used if
the percentages added to less than 100%.
:::

:::{callout-tip}
## Omitting Categories/Missing Data

The table displays Ethnicity of Students but is missing the "Other/Unknown"
category. This category contains people who did not feel they fit into any of
the ethnicity categories or declined to respond. Notice that the frequencies
do not add up to the total number of students. In this situation, create a bar
graph and not a pie chart.
:::

The following graph is the same as the previous graph but the “Other/Unknown”
percent (9.6%) has been included. The “Other/Unknown” category is large
compared to some of the other categories (Native American, 0.6%, Pacific Islander
1.0%). This is important to know when we think about what the data are telling
us.

This particular bar graph in Figure 1.8 can be difficult to understand visually. The graph in Figure 1.9 is a Pareto chart. The Pareto chart has the bars sorted from largest to smallest and is easier to read and interpret.

Pie Charts: No Missing Data The following pie charts have the “Other/Unknown” category included (since the percentages must add to 100%). The chart in Figure 1.10(b) is organized by the size of each wedge, which makes it a more visually informative graph than the unsorted, alphabetical graph in Figure 1.10(a).


## Sampling

### Simple Random Sample

Gathering information about an entire population often costs too much or is
virtually impossible. Instead, we use a **sample** of the population. A sample
**should have the same characteristics** as the population it is representing.
Most statisticians use various methods of random sampling in an attempt to
achieve this goal. This section will describe a few of the most common methods.

There are several different methods of random sampling. In each form of **random
sampling**, each member of a population initially has an equal chance of being 
selected for the sample. Each method has pros and cons. The easiest method to
describe is called a **simple random sample**. Any group of $n$ individuals is
equally likely to be chosen as any other group of $n$ individuals if the simple
random sampling technique is used. In other words, each sample of the same size
has an equal chance of being selected.

For example, suppose Lisa wants to form a four-person study group (herself and
three other people) from her pre-calculus class, which has 31 members not
including Lisa. To choose a simple random sample of size three from the other
members of her class, Lisa could put all 31 names in a hat, shake the hat, close
her eyes, and pick out three names. A more technological way is for Lisa to
first list the last names of the members of her class together with a two-digit
number:

| ID| Name| ID | Name | ID | Name |
|---|-----|----|------|----|------|
|00| Anselmo | 11 | King | 21 |	Roquero |
01	Bautista	12	Legeny	22	Roth
02	Bayani	13	Lundquist	23	Rowell
03	Cheng	14	Macierz	24	Salangsang
04	Cuarismo	15	Motogawa	25	Slade
05	Cuningham	16	Okimoto	26	Stratcher
06	Fontecha	17	Patel	27	Tallai
07	Hong	18	Price	28	Tran
08	Hoobler	19	Quizon	29	Wai
09	Jiao	20	Reyes	30	Wood
10	Khan				

Lisa can use a table of random numbers (found in many statistics books and
mathematical handbooks), a calculator, or a computer to generate random numbers.
The numbers generated are as follows:

$$0.94360; 0.99832; 0.14669; 0.51470; 0.40581; 0.73381; 0.04399$$

Lisa reads two-digit groups until she has chosen three class members (that is,
she reads 0.94360 as the groups 94, 43, 36, 60). Each random number may only
contribute one class member. If she needed to, Lisa could have generated more
random numbers.

The random numbers $0.94360$ and $0.99832$ do not contain appropriate two digit
numbers. However the third random number, $0.14669$, contains $14$ (the fourth
random number also contains $14$), the fifth random number contains $05$, and
the seventh random number contains $04$. The two-digit number $14$ corresponds
to Macierz, $05$ corresponds to Cuningham, and $04$ corresponds to Cuarismo.
Besides herself, Lisa’s group will consist of Marcierz, Cuningham, and Cuarismo.

Besides **simple random sampling*, there are other forms of sampling that
involve a chance process for getting the sample. Other well-known random 
sampling methods are the **stratified sample**, the **cluster sample*, and the
**systematic sample**.

### Stratified Sample

To choose a **stratified sample**, divide the population into groups called
strata and then take a proportionate number from each stratum. For example, you
could stratify (group) your college population by department and then choose a
proportionate simple random sample from each stratum (each department) to get a
stratified random sample. To choose a simple random sample from each department,
number each member of the first department, number each member of the second
department, and do the same for the remaining departments. Then use simple
random sampling to choose proportionate numbers from the first department and
do the same for each of the remaining departments. Those numbers picked from
the first department, picked from the second department, and so on represent
the members who make up the stratified sample.

### Cluster Sample

To choose a cluster sample, divide the population into clusters (groups) and then randomly select some of the clusters. All the members from these clusters are in the cluster sample. For example, if you randomly sample four departments from your college population, the four departments make up the cluster sample. Divide your college faculty by department. The departments are the clusters. Number each department, and then choose four different numbers using simple random sampling. All members of the four departments with those numbers are the cluster sample.

### Systematic Sample

To choose a systematic sample, randomly select a starting point and take every nth piece of data from a listing of the population. For example, suppose you have to do a phone survey. Your phone book contains 20,000 residence listings. You must choose 400 names for the sample. Number the population 1–20,000 and then use a simple random sample to pick a number that represents the first name in the sample. Then choose every fiftieth name thereafter until you have a total of 400 names (you might have to go back to the beginning of your phone list). Systematic sampling is frequently chosen because it is a simple method.

A type of sampling that is non-random is convenience sampling. Convenience sampling involves using results that are readily available. For example, a computer software store conducts a marketing study by interviewing potential customers who happen to be in the store browsing through the available software. The results of convenience sampling may be very good in some cases and highly biased (favor certain outcomes) in others.

Sampling data should be done very carefully. Collecting data carelessly can have devastating results. Surveys mailed to households and then returned may be very biased (they may favor a certain group). It is better for the person conducting the survey to select the sample respondents.

True random sampling is done with replacement. That is, once a member is picked, that member goes back into the population and thus may be chosen more than once. However for practical reasons, in most populations, simple random sampling is done without replacement. Surveys are typically done without replacement. That is, a member of the population may be chosen only once. Most samples are taken from large populations and the sample tends to be small in comparison to the population. Since this is the case, sampling without replacement is approximately the same as sampling with replacement because the chance of picking the same individual more than once with replacement is very low.

Sampling without replacement instead of sampling with replacement becomes a mathematical issue only when the population is small.

When you analyze data, it is important to be aware of sampling errors and nonsampling errors. The actual process of sampling causes sampling errors. For example, the sample may not be large enough. Factors not related to the sampling process cause nonsampling errors. A defective counting device can cause a nonsampling error.

In reality, a sample will never be exactly representative of the population so there will always be some sampling error. As a rule, the larger the sample, the smaller the sampling error.

In statistics, a sampling bias is created when a sample is collected from a population and some members of the population are not as likely to be chosen as others (remember, each member of the population should have an equally likely chance of being chosen). When a sampling bias happens, there can be incorrect conclusions drawn about the population that is being studied.

Critical Evaluation We need to evaluate the statistical studies we read about critically and analyze them before accepting the results of the studies. Common problems to be aware of include:

    Problems with samples: A sample must be representative of the population. A sample that is not representative of the population is biased. Biased samples that are not representative of the population give results that are inaccurate and not valid.
    Self-selected samples: Responses only by people who choose to respond, such as call-in surveys, are often unreliable.
    Sample size issues: Samples that are too small may be unreliable. Larger samples are better, if possible. In some situations, having small samples is unavoidable and can still be used to draw conclusions. Examples: crash testing cars or medical testing for rare conditions
    Undue influence: collecting data or asking questions in a way that influences the response
    Non-response or refusal of subject to participate: The collected responses may no longer be representative of the population. Often, people with strong positive or negative opinions may answer surveys, which can affect the results.
    Causality: A relationship between two variables does not mean that one causes the other to occur. They may be related (correlated) because of their relationship through a different variable.
    Self-funded or self-interest studies: A study performed by a person or organization in order to support their claim. Is the study impartial? Read the study carefully to evaluate the work. Do not automatically assume that the study is good, but do not automatically assume the study is bad either. Evaluate it on its merits and the work done.
    Misleading use of data: improperly displayed graphs, incomplete data, or lack of context
    Confounding: When the effects of multiple factors on a response cannot be separated. Confounding makes it difficult or impossible to draw valid conclusions about the effect of each factor.

Variation in Data

Variation is present in any set of data. For example, 16-ounce cans of beverage may contain more or less than 16 ounces of liquid. In one study, eight 16 ounce cans were measured and produced the following amount (in ounces) of beverage:

15.8; 16.1; 15.2; 14.8; 15.8; 15.9; 16.0; 15.5

Measurements of the amount of beverage in a 16-ounce can may vary because different people make the measurements or because the exact amount, 16 ounces of liquid, was not put into the cans. Manufacturers regularly run tests to determine if the amount of beverage in a 16-ounce can falls within the desired range.

Be aware that as you take data, your data may vary somewhat from the data someone else is taking for the same purpose. This is completely natural. However, if two or more of you are taking the same data and get very different results, it is time for you and the others to reevaluate your data-taking methods and your accuracy.

<iframe height="400" width="100%" frameborder="no" src="https://guillaumegilles.shinyapps.io/my_app/"> </iframe>

Variation in Samples It was mentioned previously that two or more samples from the same population, taken randomly, and having close to the same characteristics of the population will likely be different from each other. Suppose Doreen and Jung both decide to study the average amount of time students at their college sleep each night. Doreen and Jung each take samples of 500 students. Doreen uses systematic sampling and Jung uses cluster sampling. Doreen's sample will be different from Jung's sample. Even if Doreen and Jung used the same sampling method, in all likelihood their samples would be different. Neither would be wrong, however.

Think about what contributes to making Doreen’s and Jung’s samples different.

If Doreen and Jung took larger samples (i.e. the number of data values is increased), their sample results (the average amount of time a student sleeps) might be closer to the actual population average. But still, their samples would be, in all likelihood, different from each other. This variability in samples cannot be stressed enough.

Size of a Sample The size of a sample (often called the number of observations, usually given the symbol n) is important. The examples you have seen in this book so far have been small. Samples of only a few hundred observations, or even smaller, are sufficient for many purposes. In polling, samples that are from 1,200 to 1,500 observations are considered large enough and good enough if the survey is random and is well done. Later we will find that even much smaller sample sizes will give very good results. You will learn why when you study confidence intervals.

Be aware that many large samples are biased. For example, call-in surveys are invariably biased, because people choose to respond or not.

