# Definitions of Statistics, Probability, and Key Terms {.unnumbered}


## Statistics

## Probability

## Key Terms



## Exercices

### Example 1

::: {.callout-note}
## Problem

Determine what the key terms refer to in the following study. We want to know the average (mean) amount of money first year college students spend at ABC College on school supplies that do not include books. We randomly surveyed 100 first year students at the college. Three of those students spent $150, $200, and $225, respectively.
:::

::: {.callout-tip collapse="true"}
## Solution

- The **population** is all first year students attending ABC College this term.
- The **sample** could be all students enrolled in one section of a beginning statistics course at ABC College (although this sample may not represent the entire population).
- The **parameter** is the average (mean) amount of money spent (excluding books) by first year college students at ABC College this term: the population mean.
- The **statistic** is the average (mean) amount of money spent (excluding books) by first year college students in the sample.
- The **variable** could be the amount of money spent (excluding books) by one first year student. Let X = the amount of money spent (excluding books) by one first year student attending ABC College.
- The **data** are the dollar amounts spent by the first year students. Examples of the data are $150, $200, and $225.
:::

### Example 2

::: {.callout-note}
## Problem

Determine what the key terms refer to in the following study.

A study was conducted at a local college to analyze the average cumulative GPA’s
of students who graduated last year. For each statement below find the
appropriate statistical term.

1. The cumulative GPA of one student who graduated from the college last year.
2. 3.65, 2.80, 1.50, 3.90
3. A group of students who graduated from the college last year, randomly selected.
4. The average cumulative GPA of students who graduated from the college last year.
5. All students who graduated from the college last year.
6. the average cumulative GPA of students in the study who graduated from the
college last year.
:::

::: {.callout-tip collapse="true"}
## Solution

1. Population: **5**
2. Statistic: **6**
3. Parameter: **4**
4. Sample: **3**
5. Variable: **1**
6. Data: **2**
:::

### Example 3

::: {.callout-note}
## Problem

Determine what the key terms refer to in the following study.

As part of a study designed to test the safety of electric automobiles, the
National Transportation Safety Board collected and reviewed data about the
effects of an automobile crash on test dummies. Here is the criterion they
used:

| Speed at which cars crashed |	Location of “drive” (i.e. dummies) |
|:--------------------------- | :----------------------------------|
| 35 miles/hour 	          | Front Seat                         |

Cars with dummies in the front seats were crashed into a wall at a speed of 35
miles per hour. We want to know the proportion of dummies in the driver’s seat
that would have had head injuries, if they had been actual drivers. We start
with a simple random sample of 75 cars.
:::

::: {.callout-tip collapse="true"}
## Solution

- The **population** is all cars containing dummies in the front seat.
- The **sample** is the 75 cars, selected by a simple random sample.
- The **parameter** is the proportion of driver dummies (if they had been real
people) who would have suffered head injuries in the population.
- The **statistic** is proportion of driver dummies (if they had been real
people) who would have suffered head injuries in the sample.
- The **variable** $X =$ whether a dummy (if it had been a real person) would
have suffered head injuries.
- The **data** are either: yes, had head injury, or no, did not.
:::

## To recap

```{r}
library(tidyverse)
```

```mermaid
flowchart TD;
    population[Population]==> |a portion (or subset) of the population|sample(Sample);
    sample --> statistic(Statistic);
    B --> D;
    C --> D;
```

