# Introduction {.unnumbered}

> Statistics is the science of making decisions under uncertainty
> --- 1954 - Leonard J. Savage, _The Foundation of Statistics_

The science of **statistics** deals with the collection, analysis,
interpretation, and presentation of data. We see and use data in our everyday
lives. The goal of statistics is not to perform numerous calculations using
the formulas, but to gain an understanding of your data.

From the [[satistics.sample]] data, we can calculate a **statistic**. A statistic is a
number that represents a property of the sample. For example, if we consider
one math class to be a sample of the [[statistics.population]] of all math
classes, then the average number of points earned by students in that one math
class at the end of the term is an example of a statistic. The statistic is an
estimate of a population [[statistics.parameter]], in this case the mean.

## Model
> Models are mathematical tools that can describe a system and capture
> relationships in the data given to them. [...] The utility of a model
> hinges on its ability to be reductive, or to reduce complex
> relationships to simpler terms. The primary influences in the data can
> be captured mathematically in a useful way, such as in a relationship
> that can be expressed as an equation.
>
> [@978-1492096481 - Tidy Modeling with R: A Framework for Modeling in the Tidyverse]

While this list is not exhaustive, most models falls into at least one of
these  categories:

1. [[math.model.descriptive]]
2. [[math.model.inferential]]
3. [[math.model.predictive]]

## Qu'est-ce qu'un modèle

Un modèle est une **version simplifiée d'une partie du monde réel**,
dans laquelle des calculs exacts sont possibles. Un modèle est donc
un outil pour nous aider à comprendre le monde qui nous entoure. Il
permet à nos cerveaux limités d'appréhender des situations réelles de
la vie, si complexe qu'on ne peut compendre en intégralité. Aussi, les
modèles présentent une couche d'abstraction permettant d'obtenir une
version "simplifiée" la réalité [@mathematics:-a-very-short-introduction].


## Predictive Models
desc: >-
  Sometimes data are modeled to produce the most accurate prediction possible
  for new data
updated: 1733779170804
created: 1733752024603
---

For this type of model, the problem type is one of **estimation** rather
than inference. For example, the buyer is usually not concerned with a
question such as “Will I sell more than 100 copies of book X next month?”
but rather “How many copies of book X will customers purchase next month?”
[@kuhnTidyModeling2022]

## _Mechanistic Models_

## _empirically driven Models_

_Empirically driven models_ are created with more vague assumptions. These
models tend to fall into the [[ai.ml]] category. A good example is the
[[ai.ml.supervised-learning.classification.knn]] model. Given a set o
reference data, a new sample is predicted by using the values of the $K$
most similar data in thereference set.

## Inferential Models
desc: >-
  The goal of an inferential model is to produce a decision for a research
  question or to explore a specific hypothesis, similar to how statistical tests
  are used
updated: 1733778813696
created: 1733751450382
---

With help of [[statistics.inferential]], an inferential model starts
with a predefined conjecture, or idea, about a population and produces
a statistical conclusion such as an interval estimate or the rejection
of a hypothesis.

For example, the goal of a clinical trial might be to provide confirmation
that a new therapy does a better job in prolonging life than an alternative.

Inferential modeling techniques typically produce some type of probabilistic
output, such as [[statistics.inferential.p-value]], [[statistics.inferential.confidence-interval]],
or posterior probability [@kuhnTidyModeling2022].

[[statistics]] inference uses [[probability]] to determine how confident we can be that our conclusions are correct. Effective interpretation of data (inference) is based on good procedures for producing data and thoughtful examination of the data.

## Statistics

## Probability

## Key Terms

individual = people, things

In statistics, we generally want to study a population. You can think
of a population as a collection of persons, things, or objects under study. To study the population, we select a sample. The idea of sampling is to select a portion (or subset) of the larger population and study that portion (the sample) to gain information about the population. Data are the result of sampling from a population.

Because it takes a lot of time and money to examine an entire population, sampling is a very practical technique. If you wished to compute the overall grade point average at your school, it would make sense to select a sample of students who attend the school. The data collected from the sample would be the students' grade point averages. In presidential elections, opinion poll samples of 1,000–2,000 people are taken. The opinion poll is supposed to represent the views of the people in the entire country. Manufacturers of canned carbonated drinks take samples to determine if a 16 ounce can contains 16 ounces of carbonated drink.

From the sample data, we can calculate a statistic. A statistic is a number that represents a property of the sample. For example, if we consider one math class to be a sample of the population of all math classes, then the average number of points earned by students in that one math class at the end of the term is an example of a statistic. The statistic is an estimate of a population parameter. A parameter is a numerical characteristic of the whole population that can be estimated by a statistic. Since we considered all math classes to be the population, then the average number of points earned per student over all the math classes is an example of a parameter.

One of the main concerns in the field of statistics is how accurately a statistic estimates a parameter. The accuracy really depends on how well the sample represents the population. The sample must contain the characteristics of the population in order to be a representative sample. We are interested in both the sample statistic and the population parameter in inferential statistics. In a later chapter, we will use the sample statistic to test the validity of the established population parameter.

A variable, usually notated by capital letters such as X and Y, is a characteristic or measurement that can be determined for each member of a population. Variables may be numerical or categorical. Numerical variables take on values with equal units such as weight in pounds and time in hours. Categorical variables place the person or thing into a category. If we let X equal the number of points earned by one math student at the end of a term, then X is a numerical variable. If we let Y be a person's party affiliation, then some examples of Y include Republican, Democrat, and Independent. Y is a categorical variable. We could do some math with values of X (calculate the average number of points earned, for example), but it makes no sense to do math with values of Y (calculating an average party affiliation makes no sense).

Data are the actual values of the variable. They may be numbers or they may be words. Datum is a single value.

Two words that come up often in statistics are mean and proportion. If you were to take three exams in your math classes and obtain scores of 86, 75, and 92, you would calculate your mean score by adding the three exam scores and dividing by three (your mean score would be 84.3 to one decimal place). If, in your math class, there are 40 students and 22 are men and 18 are women, then the proportion of men students is  2240
  and the proportion of women students is  1840
 . Mean and proportion are discussed in more detail in later chapters.

### Variables

A **variable**, usually notated by capital letters such as $X$ and $Y$, is a
characteristic or measurement that can be determined for each member of a
[[statistics.population]]. Variables may be **numerical** or **categorical**:

- Numerical variables take on values with equal units such as weight in
pounds and time in hours.
- Categorical variables place the person or thing into a category.

If we let $X$ equal the number of points earned by one math student at the
end of a term, then $X$ is a numerical variable. If we let $Y$ be a person's
party affiliation, then some examples of $Y$ include Republican, Democrat, and
Independent. $Y$ is a categorical variable. We could do some math with values
of $X$ (calculate the average number of points earned, for example), but it
makes no sense to do math with values of $Y$ (calculating an average party
affiliation makes no sense).

#### Parameter

A parameter is a numerical characteristic of the whole [[statistics.population]]
that can be estimated by a [[statistics]]. Since we considered all math classes
to be the population, then the average number of points earned per student over
all the math classes is an example of a parameter.

### title: Observation
desc: ''
updated: 1729068716853
created: 1729068716853
isDir: false
id_imported: yc6x8d3gi8gp5kwe1l4pnns
title_imported: Observation
desc_imported: ''
updated_imported: 1711439994897
created_imported: 1711439938863
---

- Observation : propriété ou thème que l’on cherche à étudier sur les individus
  de la [[statistics.population]]. La série de ces observations forme ce qui
  s’appelle une **variable statistique**.

# Population

In [[statistics]], we generally want to study a population. You can think of a
population as a collection of persons, things, or objects under study. To study
the population, we select a [[satistics.sample]]. [@illowskyIntroductoryStatistics2e2023]



## Exercices

### Example 1

::: {.callout-note}
## Problem

Determine what the key terms refer to in the following study. We want to know the average (mean) amount of money first year college students spend at ABC College on school supplies that do not include books. We randomly surveyed 100 first year students at the college. Three of those students spent $150, $200, and $225, respectively.
:::

::: {.callout-tip collapse="true"}
## Solution

- The **population** is all first year students attending ABC College this term.
- The **sample** could be all students enrolled in one section of a beginning statistics course at ABC College (although this sample may not represent the entire population).
- The **parameter** is the average (mean) amount of money spent (excluding books) by first year college students at ABC College this term: the population mean.
- The **statistic** is the average (mean) amount of money spent (excluding books) by first year college students in the sample.
- The **variable** could be the amount of money spent (excluding books) by one first year student. Let X = the amount of money spent (excluding books) by one first year student attending ABC College.
- The **data** are the dollar amounts spent by the first year students. Examples of the data are $150, $200, and $225.
:::

### Example 2

::: {.callout-note}
## Problem

Determine what the key terms refer to in the following study.

A study was conducted at a local college to analyze the average cumulative GPA’s
of students who graduated last year. For each statement below find the
appropriate statistical term.

1. The cumulative GPA of one student who graduated from the college last year.
2. 3.65, 2.80, 1.50, 3.90
3. A group of students who graduated from the college last year, randomly selected.
4. The average cumulative GPA of students who graduated from the college last year.
5. All students who graduated from the college last year.
6. the average cumulative GPA of students in the study who graduated from the
college last year.
:::

::: {.callout-tip collapse="true"}
## Solution

1. Population: **5**
2. Statistic: **6**
3. Parameter: **4**
4. Sample: **3**
5. Variable: **1**
6. Data: **2**
:::

### Example 3

::: {.callout-note}
## Problem

Determine what the key terms refer to in the following study.

As part of a study designed to test the safety of electric automobiles, the
National Transportation Safety Board collected and reviewed data about the
effects of an automobile crash on test dummies. Here is the criterion they
used:

| Speed at which cars crashed |	Location of “drive” (i.e. dummies) |
|:--------------------------- | :----------------------------------|
| 35 miles/hour 	          | Front Seat                         |

Cars with dummies in the front seats were crashed into a wall at a speed of 35
miles per hour. We want to know the proportion of dummies in the driver’s seat
that would have had head injuries, if they had been actual drivers. We start
with a simple random sample of 75 cars.
:::

::: {.callout-tip collapse="true"}
## Solution

- The **population** is all cars containing dummies in the front seat.
- The **sample** is the 75 cars, selected by a simple random sample.
- The **parameter** is the proportion of driver dummies (if they had been real
people) who would have suffered head injuries in the population.
- The **statistic** is proportion of driver dummies (if they had been real
people) who would have suffered head injuries in the sample.
- The **variable** $X =$ whether a dummy (if it had been a real person) would
have suffered head injuries.
- The **data** are either: yes, had head injury, or no, did not.
:::

## To recap

```{r}
library(tidyverse)
```

```mermaid
flowchart TD;
    population[Population]==> |a portion (or subset) of the population|sample(Sample);
    sample --> statistic(Statistic);
    B --> D;
    C --> D;
```

## Les faits : données qu'on possède

1. Échantillon (_sample_) : sous-ensemble de la population - [[cs.data]]
2. Observation : un individu ou objet de l'échantillon
3. Statistiques : résultats déduient des données recueillis dans l'échantillon

## On essaye de trouver la vérité grâce à

1. Hypothèse : affirmation provisoire décrivant ce que les paramètres pourrait être
2. Estimation : processus pour estimer la valeur d'un paramètre de la population

title: Qualitative Data
desc: ''
updated: 1733775757555
created: 1729068716853
isDir: false
id_imported: pcxq3hqvlncj80wqe7zbwdv
title_imported: Qualitative Data
desc_imported: ''
updated_imported: 1711442135283
created_imported: 1711441971532
---

Une variable non numérique est dite **qualitative**, par exemple, la couleur des
yeux, les opinions politiques, etc. Les variables qualitatives peuvent être :

- **Ordianle** : les modalités des variables peuvent être dans un certain ordre naturel.
- **Nominale** : à l’inverse les valeurs qualitatives nominales ne peuvent être classé par ordre.

Qualitative data are the result of categorizing or describing attributes of a
[[statistics.population]]. Qualitative data are also often called categorical
data. Hair color, blood type, ethnic group, the car a person drives, and the
street a person lives on are examples of qualitative data. Qualitative data are
generally described by words or letters. For instance, hair color might be black,
dark brown, light brown, blonde, gray, or red. Blood type might be AB+, O-, or
B+. Researchers often prefer to use quantitative data over qualitative data
because it lends itself more easily to mathematical analysis. For example, it
does not make sense to find an average hair color or blood type.

[[illowskyintroductorystatistics2e2023]]

Qualitatives (_categorial data_) : données labellisées, comme _faible_,
_moyen_, _fort_. En modélisation, la prédiction de données qualitatives
est un problème de [[ds.ml.sl.class]]

title: Quantitative Data
desc: ''
updated: 1729068716853
created: 1729068716853
isDir: false
id_imported: 31ii7vbpbrtrfe5gmpndrj7
title_imported: Quantitative Data
desc_imported: ''
updated_imported: 1711442316007
created_imported: 1711442250571
---

Une variable numérique est appelée **quantitative**, c’est-à-dire qu’elle est mesurable. Les variables quantitatives peuvent être :

- **Continue** : elle peuvent prendre toute les valeurs d’intervalle fini ou infini, par exemple, les salaires, la taille du pièce, etc.
- **Discrète** ou **discontinue** : la variable discrète ne prend que des valeurs isolées les unes des autres, par exemple, le nombre d’enfants d’une famille ne peut être que 0, ou 1, ou 2, ou 3, etc.

Quantitative data are always numbers. Quantitative data are the result of counting or measuring attributes of a population. Amount of money, pulse rate, weight, number of people living in your town, and number of students who take statistics are examples of quantitative data. Quantitative data may be either discrete or continuous.

All data that are the result of counting are called quantitative discrete data. These data take on only certain numerical values. If you count the number of phone calls you receive for each day of the week, you might get values such as zero, one, two, or three.

Data that are not only made up of counting numbers, but that may include fractions, decimals, or irrational numbers, are called quantitative continuous data. Continuous data are often the results of measurements like lengths, weights, or times. A list of the lengths in minutes for all the phone calls that you make in a week, with numbers like 2.4, 7.5, or 11.0, would be quantitative continuous data.

[@illowskyIntroductoryStatistics2e2023]

1. Quantitatives (_continuous data_) : données chiffrées. Les algorithmes [[ds.ml.sl.reg]] permettent de prédire les données quantitatives ;
