# Preface {.unnumbered}


> Statistics is the science of making decisions under uncertainty
> --- 1954 - Leonard J. Savage, _The Foundation of Statistics_

The science of **statistics** deals with the collection, analysis,
interpretation, and presentation of data. We see and use data in our everyday
lives. The goal of statistics is not to perform numerous calculations using
the formulas, but to gain an understanding of your data.

From the [[satistics.sample]] data, we can calculate a **statistic**. A statistic is a
number that represents a property of the sample. For example, if we consider
one math class to be a sample of the [[statistics.population]] of all math
classes, then the average number of points earned by students in that one math
class at the end of the term is an example of a statistic. The statistic is an
estimate of a population [[statistics.parameter]], in this case the mean.

## Les faits : données qu'on possède

1. Échantillon (_sample_) : sous-ensemble de la population - [[cs.data]]
2. Observation : un individu ou objet de l'échantillon
3. Statistiques : résultats déduient des données recueillis dans l'échantillon

## On essaye de trouver la vérité grâce à

1. Hypothèse : affirmation provisoire décrivant ce que les paramètres pourrait être
2. Estimation : processus pour estimer la valeur d'un paramètre de la population

title: Qualitative Data
desc: ''
updated: 1733775757555
created: 1729068716853
isDir: false
id_imported: pcxq3hqvlncj80wqe7zbwdv
title_imported: Qualitative Data
desc_imported: ''
updated_imported: 1711442135283
created_imported: 1711441971532
---

Une variable non numérique est dite **qualitative**, par exemple, la couleur des
yeux, les opinions politiques, etc. Les variables qualitatives peuvent être :

- **Ordianle** : les modalités des variables peuvent être dans un certain ordre naturel.
- **Nominale** : à l’inverse les valeurs qualitatives nominales ne peuvent être classé par ordre.

Qualitative data are the result of categorizing or describing attributes of a
[[statistics.population]]. Qualitative data are also often called categorical
data. Hair color, blood type, ethnic group, the car a person drives, and the
street a person lives on are examples of qualitative data. Qualitative data are
generally described by words or letters. For instance, hair color might be black,
dark brown, light brown, blonde, gray, or red. Blood type might be AB+, O-, or
B+. Researchers often prefer to use quantitative data over qualitative data
because it lends itself more easily to mathematical analysis. For example, it
does not make sense to find an average hair color or blood type.

[[illowskyintroductorystatistics2e2023]]

Qualitatives (_categorial data_) : données labellisées, comme _faible_,
_moyen_, _fort_. En modélisation, la prédiction de données qualitatives
est un problème de [[ds.ml.sl.class]]

title: Quantitative Data
desc: ''
updated: 1729068716853
created: 1729068716853
isDir: false
id_imported: 31ii7vbpbrtrfe5gmpndrj7
title_imported: Quantitative Data
desc_imported: ''
updated_imported: 1711442316007
created_imported: 1711442250571
---

Une variable numérique est appelée **quantitative**, c’est-à-dire qu’elle est mesurable. Les variables quantitatives peuvent être :

- **Continue** : elle peuvent prendre toute les valeurs d’intervalle fini ou infini, par exemple, les salaires, la taille du pièce, etc.
- **Discrète** ou **discontinue** : la variable discrète ne prend que des valeurs isolées les unes des autres, par exemple, le nombre d’enfants d’une famille ne peut être que 0, ou 1, ou 2, ou 3, etc.

Quantitative data are always numbers. Quantitative data are the result of counting or measuring attributes of a population. Amount of money, pulse rate, weight, number of people living in your town, and number of students who take statistics are examples of quantitative data. Quantitative data may be either discrete or continuous.

All data that are the result of counting are called quantitative discrete data. These data take on only certain numerical values. If you count the number of phone calls you receive for each day of the week, you might get values such as zero, one, two, or three.

Data that are not only made up of counting numbers, but that may include fractions, decimals, or irrational numbers, are called quantitative continuous data. Continuous data are often the results of measurements like lengths, weights, or times. A list of the lengths in minutes for all the phone calls that you make in a week, with numbers like 2.4, 7.5, or 11.0, would be quantitative continuous data.

[@illowskyIntroductoryStatistics2e2023]

1. Quantitatives (_continuous data_) : données chiffrées. Les algorithmes [[ds.ml.sl.reg]] permettent de prédire les données quantitatives ;
