# Analyzing Quantitative Data

## Visualization

histogram = on continuous variable

## Computing

After the measures of central tendency/position (mean, mode, median),
variance is a measure of dispersion (like the range) that allows us to
assess the deviations of each value from the mean.

### Mean

#### Statistical Mean

La moyenne, notée m ou x- (x barre), est le centre de gravité

#### Arithmetic Mean

#### Weighted Mean

La moyenne arithmétique est la somme des valeurs divisée par le nombre d'individus :

$$
\bar{X} = \frac{1}{n} \cdot \sum_{i = 1}^n x_i
$$

#### Average or mean ?

The words "[[statistical-mean]]" and "average" are often used interchangeably.
The substitution of one word for the other is common practice. The technical
term is `arithmetic mean`, and "average" is technically a center location.
However, in practice among non-statisticians, "average" is commonly accepted
for `arithmetic mean`.

## Median

La **médiane**, désignée par Me, est la valeur de la variable statistique qui sépare la population ou l’échantillon en deux sous-ensembles égaux. Il y a 50% de la population au-dessus de la médiane et 50% de la population en dessous de la médiane.

La médiane est la valeur centrale qui partage l'échantillon en 2 groupes de même effectif : 50 % au-dessus et 50 % en dessous. La médiane peut avoir une valeur différente de la moyenne. En France (et d'ailleurs dans la plupart des pays), le salaire médian est inférieur au salaire moyen : il y a beaucoup de smicards et peu de gros salaires. Cependant, les gros salaires tirent la moyenne vers le haut.

En général, une médiane est, dans une série ordonnée, une valeur M telle qu'il y ait autant de valeurs supérieures ou égales à M que de valeur inférieures ou égales à M. exemple : 1 3 5 7 9 la médiane est 5

## Mode

Le **mode**, désigné par Mo, est la valeur de la variable statistique la plus fréquente. Dans le cas d’une variable statistique continue, le mode est appelé **classe modale**. Le mode, ou classe modale, n’est pas obligatoirement unique. Il peut exister plusieurs valeurs les plus fréquente dans une population ou échantillon.

# Measure of Variability

La variance est pour l'inférence (cf. les formules des stats inféretielles)
et l'écart type est pour la stat descriptive car on dans la même ordre d'unité que le dataset.

Après les mesures de centre/position (moyenne, mode, médiane), la variance
est une mesure de dispoersion (comme l'étendu) permet de mesurer les écart
de chaque valeur par rapport à la moyenne.

Si on étudie la population: $N$

$\sigma^2 = \frac{\sum(x - moyenne)^2}{N}$

Si on étudie un échantillon: $n$

$s^2 = \frac{\sum(x - moyenne)^2}{n-1}$

Finalement, la variance est une moyenne de carrés.

## comparer des variances entres elles.

Test F de Fisher - Senedecor

F = variance la plus élevé / variance la plus faible

## l'écart-type est la racine carré de la variance
               Variance     Ecart-type
population      sigma^2       sigma
échantillon      s^2           s

