---
title: Syllabus
# Foam graph
tags: [Github-page, IBS]
---

Guillaume Gilles (guillaume.gilles@essca.eu)

### Course Description

### Course Learning Outcomes, Objectives

### Course Calendar

| Date | Topic                                                        | Textbook's Chapters |
| :--: | ------------------------------------------------------------ | :-----------------: |
|  #1  | Sets and Combinatorial Analysis                              |                     |
|  #2  | Calculation of probabilities                                 |                     |
|  #3  | Discrete random variable                                     |                     |
|  #4  | Continuous random variable                                   |                     |
|  #5  | Lab on Excel                                                 |                     |
|  #6  | Review of descriptive statistics                             |                     |
|  #7  | Estimation                                                   |                     |
|  #8  | Hypothesis Testing - Test of conformity to a reference value |                     |
|  #9  | Hypothesis testing - Comparison test                         |                     |
| #10  | Lab on Excel                                                 |                     |
| #11  | Test ANOVA                                                   |                     |
| #12  | Chi-Square Test                                              |                     |
| #13  | Linear correlation coefficient Test                          |                     |
| #14  | Lab on Excel                                                 |                     |

### Course Grades:

1. Midterm Exam: MCQ for 35% of your grade
2. Final Exam: 65% of your grade

### Course goals & objectives

### Class meetings

This class is taught for students PGE programm during the spring semester at Bordeaux

### Required materials

### Class meetings

### Exams

### Work load

You are expected to put in about 4-6 hours of work / week outside of class. Some of you will do well with less time than this, and some of you will need more
